name: CI

on: [push]

permissions:
  contents: read
  packages: write

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php_versions: ['7.4', '8.0', '8.1']

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          dev: yes
          php_version: ${{ matrix.php_versions }}
      - name: Run tests
        uses: php-actions/phpunit@v3
        with:
          version: 9
          php_version: ${{ matrix.php_versions }}
          configuration: phpunit.xml.dist
